### ISSUE TITLE
Standalone application?

### ISSUE THREAD

**Issue by rraallvv** [solettaproject/soletta-visual-editor#10]
Is there a version of the editor being distributed as a standalone application?
Any planes to pack it like so? I wonder if something like [Electron](http://electron.atom.io) could be used without too much trouble.

**Comment by davidmaxwaterman** [comment]
Hi...thanks for you interest :)

AFAIK, there are no versions distributed at all and no plans to do so. The intention is for the user to download and build the app from here on github. I don't see how it could be made to work with Electron, though I didn't look too hard.

I might investigate making a hosted version and making it available as a Progressive Web App.

Thanks for the suggestion.

**Comment by rraallvv** [comment]
Thanks for your replay, I'll keep this thread updated in case I can successfully pack the editor with Electron. Regarding a Progressive Web App for Soletta, it definitely looks interesting. I tried https://app.flowhub.io on my iPad and it didn't load from mobile Safari (haven't tried other browsers though), I'd bet a Progressive Web App would do the job on mobile platforms.

**Comment by davidmaxwaterman** [comment]
Progressive Web Apps would be just like a normal web app on mobile safari (it doesn't implement Service Worker). Actually, it would be a pain to have to make it work on that because they make it quite difficult to debug that platform (and it seems to be different even to safari on iOS). I suppose I would have to though, but the primary platform would be chrome.

**Comment by rraallvv** [comment]
@davidmaxwaterman I see, thanks for the clarification.
