### ISSUE TITLE
using very old version of polymer

### ISSUE THREAD

**Issue by ghost** [solettaproject/soletta-visual-editor#8]
polymer v 1.0 is much faster runtime. worth using

polyup will try to upgrade the code automagically for you.

**Comment by davidmaxwaterman** [comment]
This project has a dependency on noflo which uses polymer 0.5, and it can't be combined with 1.0. There is talk of noflo upgrading to 1.0 (or not using polymer at all), at which point an upgrade can be considered.
Is there a problem with performance? I haven't noticed anything particularly slow. If you have a test case (eg a project file) that is slow, then it would be useful to get a copy of it.

**Comment by ghost** [comment]
Nope i dont have a test case issue at all.

But, i reaised this because i use polymer 1.1, and i used to use polymer 0.5. Have dont maybe 10 projects with Polymer.
Polymer 1.0 is pretty much a rewrite.
Its faster, easier, works on all browsers better, and has much better control of the styling ( i hate css btw).
Its just more stable basically

**Comment by ghost** [comment]
Also the upgrade tool is pretty good
https://github.com/PolymerLabs/polyup

as you say though its not your code, Its the noflo / grid team's code.

**Comment by davidmaxwaterman** [comment]
Yes, I'm very familiar with Polymer 1.1, so I'm afraid you're not telling me anything I don't already know. I've attempted to use polyup in the past on a different project, and, while helpful, it really isn't a complete solution to the upgrade problem (not least because I was using an earlier version and they've fixed many bugs recently which means I have to re-run it). I imagine it might be better for _this_ project, though, since it is relatively simple, and there are several tests (wct wasn't around in time for the other project). It would be much better if the different Polymer versions worked together, then the upgrade process could be done one element at a time - perhaps future upgrades will allow this.
Anyway, unfortunately, at the moment, there's nothing to be done.

Are you actually using this tool and finding it useful at all?

**Comment by ghost** [comment]
I am not using it yet.
I need something like soletta for IOT platform, and II am using polymer 1.1 for other parts.

In terms of useful absolutely yes.
Modelling fbp is exactly what Ineed to allow people to write workflows.

The duktape stuff also looks great for me. 

I am still looking into hardware platform though.

**Comment by davidmaxwaterman** [comment]
OK, so I hope you've managed to get in touch with the Soletta guys since they can probably help you get going with it. I think there may also be other options for generating IoT networks, so you might want to ask about that.
I'll close this issue - but thanks for your interest, and best of luck using Soletta.

**Comment by bdilly** [comment]
Hi @gedw99 ,

I'm one of Soletta developers. We're interested to receive users feedback and know more about use cases and requirements. If you want to help with that, please let me know.

My email is bruno.dilly@intel.com

**Comment by ghost** [comment]
I am also now using and is working OK.

@bdilly
I sent you an email and my contacts just now.
Thanks for reaching out
